-- 기존 테이블, 시퀀스 삭제 (존재할 경우 대비)
DROP TABLE TODO CASCADE CONSTRAINTS;
DROP TABLE TODO_CATEGORY CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_TODO;
DROP SEQUENCE SEQ_TODO_CATEGORY;

-- 카테고리 테이블 생성 (soft delete용 DEL_YN 추가)
CREATE TABLE TODO_CATEGORY (
    CATEGORY_NO   NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(50) NOT NULL UNIQUE,
    DEL_YN        CHAR(1) DEFAULT 'N' CHECK (DEL_YN IN ('Y','N'))
);

-- 할 일 테이블 생성 (soft delete용 DEL_YN 추가)
CREATE TABLE TODO (
    TODO_NO       NUMBER PRIMARY KEY,
    CATEGORY_NO   NUMBER,
    TODO_CONTENT  VARCHAR2(200) NOT NULL,
    DUE_DATE      DATE NOT NULL,
    IS_DONE       CHAR(1) DEFAULT 'N' CHECK (IS_DONE IN ('Y','N')),
    CREATED_DATE  TIMESTAMP DEFAULT SYSDATE,
    MODIFIED_DATE TIMESTAMP DEFAULT SYSDATE,
    DEL_YN        CHAR(1) DEFAULT 'N' CHECK (DEL_YN IN ('Y','N')),
    FOREIGN KEY (CATEGORY_NO) REFERENCES TODO_CATEGORY(CATEGORY_NO)
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_TODO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TODO_CATEGORY START WITH 1 INCREMENT BY 1 NOCACHE;

-- 카테고리 더미 데이터
INSERT INTO TODO_CATEGORY VALUES (1, '집안일', 'N');
INSERT INTO TODO_CATEGORY VALUES (2, '공부',   'N');
INSERT INTO TODO_CATEGORY VALUES (3, '쇼핑',   'N');
INSERT INTO TODO_CATEGORY VALUES (4, '운동',   'N');
INSERT INTO TODO_CATEGORY VALUES (5, '기타',   'N');

-- 할 일 더미 데이터
INSERT INTO TODO (TODO_NO, TODO_CONTENT, CATEGORY_NO, DUE_DATE, IS_DONE, DEL_YN)
VALUES (SEQ_TODO.NEXTVAL, '청소기 돌리기', 1, TO_DATE('2025-07-30','YYYY-MM-DD'), 'N', 'N');

INSERT INTO TODO (TODO_NO, TODO_CONTENT, CATEGORY_NO, DUE_DATE, IS_DONE, DEL_YN)
VALUES (SEQ_TODO.NEXTVAL, '스프링 복습하기', 2, TO_DATE('2025-07-29','YYYY-MM-DD'), 'Y', 'N');

INSERT INTO TODO (TODO_NO, TODO_CONTENT, CATEGORY_NO, DUE_DATE, IS_DONE, DEL_YN)
VALUES (SEQ_TODO.NEXTVAL, '마트에서 장보기', 3, TO_DATE('2025-07-29','YYYY-MM-DD'), 'Y', 'N');

INSERT INTO TODO (TODO_NO, TODO_CONTENT, CATEGORY_NO, DUE_DATE, IS_DONE, DEL_YN)
VALUES (SEQ_TODO.NEXTVAL, '헬스장 가기', 4, TO_DATE('2025-07-31','YYYY-MM-DD'), 'N', 'N');

INSERT INTO TODO (TODO_NO, TODO_CONTENT, CATEGORY_NO, DUE_DATE, IS_DONE, DEL_YN)
VALUES (SEQ_TODO.NEXTVAL, '친구 생일선물 사기', 5, TO_DATE('2025-08-01','YYYY-MM-DD'), 'N', 'N');

-- 커밋
COMMIT;
